name: RocketLaunch
version: '${project.version}'
main: com.spaceniklas.rocketlaunch.Rocketlaunch
api-version: 1.19
authors: [ SpaceNiklas ]
description: If you right click holding a rocket you are set FLYING!
website: www.spaceniklas.com
